// Common English words that must NEVER become pronunciation aliases — a
// mis-hearing that lands on one of these would rewrite ordinary dictation
// (e.g. alias "tie" → "Thys" would corrupt "black tie event"). Curated from
// high-frequency word lists; lowercase. Mirrored in the dashboard repo
// (Speakflow Dashboard src/lib/common-words.ts) — keep both in sync. The
// dashboard filters at harvest time; this copy is the defensive re-check at
// application time (a hand-edited DB row must not corrupt dictations).

const WORDS = `the be to of and a in that have i it for not on with he as you do at this but his by from they we say her she or an will my one all would there their what so up out if about who get which go me when make can like time no just him know take people into year your good some could them see other than then now look only come its over think also back after use two how our work first well way even new want because any these give day most us is are was were been has had did does having am
man woman child boy girl person family friend house home room door window water food coffee tea milk bread meat fruit apple money car road street city town country world school office shop store church hospital hotel game team ball book paper pen phone computer screen light fire air earth sun moon star tree flower grass animal dog cat bird fish horse cow sheep chicken hand head eye ear nose mouth face hair arm leg foot heart body word name number letter question answer story music song film movie news picture colour color sound voice line side end part piece bit lot group half top bottom front middle place area point plan idea problem reason result change help need call talk speak tell ask show start stop run walk sit stand open close read write hear listen watch play win lose find lose keep hold bring carry send buy sell pay cost meet leave stay live sleep eat drink cook wash clean drive ride fly swim jump climb fall break cut hit push pull throw catch turn move wait hope wish love hate feel seem sound smell taste touch remember forget learn teach study understand believe agree decide choose try begin finish continue happen become grow rain snow wind storm cloud sky sea river lake mountain hill field farm garden park bridge station airport train bus boat ship plane bike
big small large little long short tall high low old young new early late fast slow hot cold warm cool dry wet hard soft easy difficult heavy light strong weak rich poor happy sad angry afraid tired hungry thirsty sick healthy safe dangerous clean dirty full empty open closed right wrong true false real free busy quiet loud dark bright deep shallow wide narrow thick thin near far left right straight round flat sharp smooth rough sweet sour bitter fresh nice good bad great terrible beautiful ugly pretty handsome interesting boring important main special different same similar whole own other another next last past future present ready sure certain possible impossible necessary common rare simple complex modern ancient national international local private public general particular
monday tuesday wednesday thursday friday saturday sunday january february march april may june july august september october november december spring summer autumn winter today tomorrow yesterday morning afternoon evening night week month year hour minute second moment while during before after until since again always never often sometimes usually rarely soon already yet still almost quite very really too enough more less most least much many few several both either neither each every some any none nothing something anything everything someone anyone everyone nobody somewhere anywhere everywhere here there where why how what when who whose which whether yes no maybe perhaps please thanks thank sorry hello goodbye okay
zero one two three four five six seven eight nine ten eleven twelve twenty thirty forty fifty hundred thousand million first second third fourth fifth once twice
should must might may shall ought need dare used going gonna want wanna let make made get got said says told asked came went gone done seen known taken given found thought brought bought caught taught left felt kept held meant sent spent built lost paid heard read stood understood wrote written spoke spoken broke broken chose chosen drove driven ate eaten fell fallen flew flown forgot forgotten froze frozen grew grown hid hidden knew drew drawn rose risen ran sang sung sat slept sold sought shone shot showed shown shut sang spoke sprang stole stolen stuck stung swore sworn swam swum threw thrown woke woken wore worn
about above across after against along among around at before behind below beneath beside between beyond by down during except for from in inside into near of off on onto out outside over past through throughout till to toward under underneath until up upon with within without
actually basically certainly clearly definitely especially exactly finally generally honestly obviously probably quickly really seriously simply slowly suddenly totally truly usually
business company work job boss manager customer client meeting project report email message call price sale offer deal market product service quality team member staff office manager plan budget cost profit tax bill account bank card cash credit order invoice quote contract deadline schedule task list note item detail level rate percent total amount value price share stock trade brand
internet website email online app software program system data file folder link page site network password account user login post share like follow search click type save delete update download upload install screen keyboard mouse printer camera video photo image audio speaker`

export const COMMON_WORDS: Set<string> = new Set(
  WORDS.split(/\s+/).map((w) => w.trim()).filter(Boolean),
)
